config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  
  def home
  
  end
  def about
    
  end
  def help
  
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  
  def new
    @todo = Todo.new
  end
  
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Task was created successfully!"
      redirect_to todo_path(@todo)
    else 
      render 'new'
    end
  end
  
  def show

  end
  
  def edit

  end
  
  def update

    if @todo.update(todo_params)
      flash[:notice] = "Task was sucessfully updated!"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end
  
  def index
    @todos = Todo.all
  end
  
  def destroy

    @todo.destroy
    flash[:notice] = "Task was sucessfully deleted!"
    redirect_to todos_path
  end
  
  private 
    
    def todo_params
      params.require(:todo).permit(:name, :description)
    end
  
    def set_todo
      @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/layouts/_inav.html.erb
<div id="navbar" class="w3-bar w3-blue w3-border w3-xlarge">
  <a href="/" class="w3-bar-item w3-button w3-white"><i class="fa fa-home"></i></a>
  <a href="/todos" class="w3-bar-item w3-button"><i class="fa fa-plus-square-o"></i></a>
  <a onclick="edit()" class="w3-bar-item w3-button"><i class="fa fa-pencil-square-o"></i></a>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="w3-panel w3-blue w3-display-container">
    <span onclick="this.parentElement.style.display='none'" class="w3-button w3-blue w3-large w3-display-topright">&times;</span>
      <p><%= msg %></p>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="w3-bar w3-blue w3-border w3-xlarge">
  <a href="/todos" class="w3-bar-item w3-button w3-white"><i class="fa fa-home"></i></a>
  <a href="/todos/new" class="w3-bar-item w3-button"><i class="fa fa-plus-square-o"></i></a>
  <a onclick="edit()" class="w3-bar-item w3-button"><i class="fa fa-pencil-square-o"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-trash-o"></i></a>
  <a href="/" class="w3-bar-item w3-button"><i class="fa fa-sign-out"></i></a>
</div>

<script>
function edit() {
    var person = prompt("Please enter task ID", "1");
    if (person != null) {
window.location.href = "/todos/" + person + "/edit"
    } else {
      window.location.href = "/todos/1/edit"
    }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/help.html.erb
<h1>This is the help page</h1>

app/views/pages/home.html.erb
<h1>Hello World!</h1>
<h2>This is a test</h>

app/views/todos/_form.html.erb
<style>
.w3-button {width:150px;}
</style>
<% if @todo.errors.any? %>

<h2>The following errors prevented the task from being saved</h2>
<ul>
<% @todo.errors.full_messages.each do |msg| %>
<ul><li><%= msg %></li></ul>
<% end %>
</ul>

<% end %>


<%= form_for @todo do |f| %>

<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :description %><br>
<%= f.text_area :description %>
</p>

<p>
<%= f.submit :class => 'w3-button, w3-blue' %>
</p>

<% end %>

app/views/todos/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="w3-padding-small">
<h1>Edit an existing Task</h1>
<%= render 'form' %>
</div>

app/views/todos/index.html.erb
    <%= render 'layouts/navbar' %>
<div class="w3-padding-small">
  <h1>Listing of Tasks</h1>
  <table class="w3-table-all w3-hoverable">
    <tr class="w3-blue">
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
   <% @todos.each do |todo| %>
      <tr>
        <td style="width: 15%"><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td style="width: 20px"><%= link_to edit_todo_path(todo) do %>
        <i class="fa fa-pencil-square-o">
          <% end %></td>
        <td style="width: 20px"><%= link_to todo_path(todo) do%>
        <i class="fa fa-eye">
        <% end %></td>
        <td>
          <%= link_to todo_path(todo), method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="fa fa-trash">
          <% end %></td>
      </tr>
    <% end %>
  </table>
  
  
</div>

app/views/todos/new.html.erb
<%= render 'layouts/navbar' %>
<div class="w3-padding-small">
<h1>Create a new Task</h1>
<%= render 'form' %>
</div>

app/views/todos/show.html.erb
<%= render 'layouts/navbar' %>
<div class="w3-padding-small">
<h1>Showing a Task</h1>
<p>
  name: <%= @todo.name %>
</p>
<p>
  description: <%= @todo.description %>
</p>
</div>